### PR TITLE
Add stripslashes to message before sending the email. #92

### PR DESCRIPTION
**Pull request by pippinsplugins**
#92

### CODE REVIEW

**Comment by Desertsnowman** [comment]
Thanks.  I have been putting it off since I've been planning the merger of my caldera SMTP plugin.  But Im still debating that.

**Comment by Desertsnowman** [comment]
If you're interested, take a look at the 2.0 branch. It's an overhaul of the ui. Not fully functional though.

**Comment by pippinsplugins** [comment]
Cool, will do!

**Comment by Desertsnowman** [comment]
It's still early in dev. Only spent a day on it. And the nested grid divisions are tricky. But it gives an idea. Also the code is significantly cleaner, with unit testing prepped. https://scrutinizer-ci.com/g/Desertsnowman/Caldera-Forms/

**Pull request merged**
